plugins:
  - jekyll-seo-tag

title: امید کیانی، مربی پایه یک
email: omidkiani136700@gmail.com
description: > 
امید کیانی، مربی پایه یک، آموزش تخصصی پایه یک در شهر اهواز
طراحی شده توسط سعید حیدری زارعی
url: "https://kiani2018.github.io" 

google_analytics_ua: UA-111756898-2